/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://hc7ptqtja5bzpg576iov7527pm.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3ajduac2xnhq7pg4i4d6sznx7i",
    "aws_cognito_identity_pool_id": "eu-west-2:2cac0338-6ada-4791-9890-b98533608480",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_PNZB8sqXQ",
    "aws_user_pools_web_client_id": "6bibq5jad8mcru0ksqosf3ebg3",
    "oauth": {}
};


export default awsmobile;
